### ISSUE TITLE
Introduce the extension traits for the contract type

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#86]
We are getting to the point where many things are generated, and there is more than one macro invocation in a single crate. It creates an issue of naming collisions when entities are generated in a single module. It could be solved by forcing devs to have only one macro invocation per module. Still, it is significantly limiting in terms of contract structure, and it is beneficial to leave as much freedom as possible to the developer. 

The other idea is to keep generated entities in some enclosed scope and then expose some traits on contracts that access generated entities instead of modules. This makes the naming problem easier. It also vastly improves documentation easiness and might make LSP work better.

What I imagine is, for example, the `sylvia::Contract` trait looking like this:

```rust
trait Contract {
  type InstantiateMsg;
  type ExecMsg;
  type QueryMsg;
  type MigrationMsg;
}
```

And then, there is implementation generated for the contract:

```rust
impl Contract for Cw20Contract {
  type InstantiateMsg = msg::InstantiateMsg;
  type ExecMsg = msg::ExecMsg;
  type QueryMsg = msg::QueryMsg;
  type MigrationMsg = sylvia::cw_std::Empty;
}
```

It could be tempting to use this trait also to add all other meta-info, let say:

```rust
trait Contract {
  type InstantiateMsg;
  type ExecMsg;
  type QueryMsg;
  type MigrationMsg;
  
  type MtHelper = multi_test::Cw20Contract;
  type MtCodeId = multi_test::CodeId;
}
```

But then, the trait implementation would have to be split between macros, which seems impossible. Also, sometimes some entities need to be generated, which would complicate such a case. The solution is to have more crates:

```rust
trait Multitest {
  type CodeId = cw20::multi_test::CodeId;
  type Contract = cw20::multi_test::Contract;
}
```

Then instead of accessing generated entities directly, one imports the proper trait and uses the contract type:

```rust
let code_id = Cw20Contract::CodeId::store(&App);
```

This would make finding and accessing generated entities easier, as you don't need to remember Sylvia naming patterns. The next step is to add the `sylvia::prelude` module with all those traits, so it is easier to import everything at once with a prelude pattern.

The final step would be to hide generated implementations using generated namespace, which the user will not likely use. This would free the names generated by Sylvia for dev, as they are meant to be accessed by exposed traits, which are very quickly findable.

**Comment by jawoznia** [comment]
To avoid issues with namespaces when accessing the `Proxy` helper we should remove the `(module=...)` and encourage users to wrap the `interface` and it's implementation on the `contract` in the same module if `interface` and `contract` are defined in the same file.

Also this approach as I understand aims to implement these traits on the `Contract`. The issue is with accessing `Proxy` generated by `interfaces` and it won't help with that.

Possible solution here could be to generate `Proxy` with `interface` expansion and then in `impl Interface for Contract` generate a `trait` defining accessors to the methods of the `interface` and implement it on the `Proxy`. Here is possible solution https://github.com/jawoznia/multitest_poc/tree/proxy_for_traits.
Unfortunately I wasn't able to make it work without introducing the module in which `Proxy` is defined.
So there is `use crate::counter;` and then we can generate `counter::ExecMsg`, `counter::multitest_utils::CounterProxy`.
